### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by saikek** [zattoo/output#3]
```
(node:1523) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'number' of undefined
    at run (/home/runner/work/_actions/zattoo/output/v1/dist/index.js:7383:53)
    at Object.676 (/home/runner/work/_actions/zattoo/output/v1/dist/index.js:7445:1)
    at __webpack_require__ (/home/runner/work/_actions/zattoo/output/v1/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/zattoo/output/v1/dist/index.js:43:19)
    at /home/runner/work/_actions/zattoo/output/v1/dist/index.js:47:18
    at Object.<anonymous> (/home/runner/work/_actions/zattoo/output/v1/dist/index.js:50:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
(node:1523) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1523) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
```
name: Do things
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.step1.outputs.url }} # map step output to job output
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - uses: zattoo/output@v1
        with:
          token: ${{github.token}}
          sources: 'test/HELLO_WORLD.md'
```

**Comment by dobladov** [comment]
The action only works in pull requests, if is triggered `on: push` there is no PR comment to modify.

```
on:
  pull_request:
    types: [
        opened,
        ready_for_review,
        reopened,
        synchronize,
    ]
    branches:
      - hotfix
      - master
```

**Comment by saikek** [comment]
Ok, is there something else that i've missed ? 

```
Run jdvr/action-add-comment@main
  with:
    comment: Current build $BUILD_NUMBER has passed ✅
  env:
    BUILD_NUMBER: 1234
    GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }}
running with Current build $BUILD_NUMBER has passed ✅
Error: This action must run only on PR triggered workflows
Error: TypeError: Cannot read property 'number' of undefined
```

## That's under pull request:
https://github.com/shafr/test/pull/1

**Comment by saikek** [comment]
Ok, maybe it's messing up data between steps & my echo does not work properly from previous step:
```
      - name: Echo file
        run: echo "test 1234567890" >> file.md        
      - uses: zattoo/output@v1
        with:
          token:  ${{github.token}}
          sources: 'file.md'
```

Anyway, even if i'm referencing path `dimi/HELLO_WORLD.md` there's no data.
